# Generated by Django 4.1.6 on 2023-04-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_following',
            field=models.IntegerField(default=0),
        ),
    ]
